### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by icebob** [icebob/vue-form-generator#175]
There are some recent changes what we need to update in documentation too.

- [x] `change` property in schema of file input #173
- [x] supported async validators #171
- [x] custom validation message for fields #169
- [x] supported string-based validators #167
- [x] vue-multiselect fixed #30 but in beta15, but they expanded [CSS from JS bundle](http://monterail.github.io/vue-multiselect/#sub-getting-started).

**Comment by dflock** [comment]
Working on this...

**Comment by dflock** [comment]
Here is where this is happening: https://www.gitbook.com/book/icebob/vueformgenerator/changes/8

So far, added a validation section and documented the validation stuff - at least as far as I understand it. Will need checking!

**Comment by dflock** [comment]
OK, I think this is done.

Not really sure about the changes for #173 - I added the `value` attribute to the attribute compatibility table, because the file input makes the files available there, I think? I also fixed up some breakage in that table.

**Comment by icebob** [comment]
Nice job! Thank you very much! :1st_place_medal:
